// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"design/01-visual-style-analysis.md": () => import("../content/ebook/design/01-visual-style-analysis.md?collection=docs"), "design/02-design-system-recommendations.md": () => import("../content/ebook/design/02-design-system-recommendations.md?collection=docs"), "design/03-issues-and-fixes.md": () => import("../content/ebook/design/03-issues-and-fixes.md?collection=docs"), "design/04-modification-plan.md": () => import("../content/ebook/design/04-modification-plan.md?collection=docs"), "design/brand.md": () => import("../content/ebook/design/brand.md?collection=docs"), "exercises/stage-1.md": () => import("../content/ebook/exercises/stage-1.md?collection=docs"), "exercises/stage-2.md": () => import("../content/ebook/exercises/stage-2.md?collection=docs"), "exercises/stage-3.md": () => import("../content/ebook/exercises/stage-3.md?collection=docs"), "exercises/stage-4.md": () => import("../content/ebook/exercises/stage-4.md?collection=docs"), "exercises/stage-5.md": () => import("../content/ebook/exercises/stage-5.md?collection=docs"), "exercises/stage-6.md": () => import("../content/ebook/exercises/stage-6.md?collection=docs"), "exercises/stage-7.md": () => import("../content/ebook/exercises/stage-7.md?collection=docs"), "exercises/stage-8.md": () => import("../content/ebook/exercises/stage-8.md?collection=docs"), "guide/daily-digest.md": () => import("../content/ebook/guide/daily-digest.md?collection=docs"), "guide/debugging-lessons.md": () => import("../content/ebook/guide/debugging-lessons.md?collection=docs"), "guide/deployment-lessons.md": () => import("../content/ebook/guide/deployment-lessons.md?collection=docs"), "guide/environment.md": () => import("../content/ebook/guide/environment.md?collection=docs"), "guide/git-workflow.md": () => import("../content/ebook/guide/git-workflow.md?collection=docs"), "guide/integration-lessons.md": () => import("../content/ebook/guide/integration-lessons.md?collection=docs"), "guide/project-structure.md": () => import("../content/ebook/guide/project-structure.md?collection=docs"), "guide/roadmap.md": () => import("../content/ebook/guide/roadmap.md?collection=docs"), "index.md": () => import("../content/ebook/index.md?collection=docs"), "stages/stage-1.md": () => import("../content/ebook/stages/stage-1.md?collection=docs"), "stages/stage-2.md": () => import("../content/ebook/stages/stage-2.md?collection=docs"), "stages/stage-3.md": () => import("../content/ebook/stages/stage-3.md?collection=docs"), "stages/stage-4.md": () => import("../content/ebook/stages/stage-4.md?collection=docs"), "stages/stage-5.md": () => import("../content/ebook/stages/stage-5.md?collection=docs"), "stages/stage-6.md": () => import("../content/ebook/stages/stage-6.md?collection=docs"), "stages/stage-7.md": () => import("../content/ebook/stages/stage-7.md?collection=docs"), "stages/stage-8.md": () => import("../content/ebook/stages/stage-8.md?collection=docs"), }),
};
export default browserCollections;